//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rebus.Client.Windows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rebus.Client.Windows.resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits: {0::c0}.
        /// </summary>
        internal static string CreditFormat {
            get {
                return ResourceManager.GetString("CreditFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat.
        /// </summary>
        internal static string DefeatMessage {
            get {
                return ResourceManager.GetString("DefeatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Everyone).
        /// </summary>
        internal static string EveryoneMessage {
            get {
                return ResourceManager.GetString("EveryoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {7} defended {1} ({2} versus {3}). {0} destroyed {4}, captured {5}, and retreated {6}. We destroyed {4}..
        /// </summary>
        internal static string InvaderDefeatFormat {
            get {
                return ResourceManager.GetString("InvaderDefeatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We conquered {1} ({3} versus {2}) from {7}. We destroyed {4} and captured {5}. We lost {4}; {6} retreated..
        /// </summary>
        internal static string InvaderVictoryFormat {
            get {
                return ResourceManager.GetString("InvaderVictoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License notice for {0}.
        /// </summary>
        internal static string LicenseFormat {
            get {
                return ResourceManager.GetString("LicenseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password is incorrect..
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string NoneMessage {
            get {
                return ResourceManager.GetString("NoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} conquered {1} ({3} versus {2}). {0} destroyed {4}, captured {5}, and retreated {6}. We destroyed {4}..
        /// </summary>
        internal static string OccupantDefeatFormat {
            get {
                return ResourceManager.GetString("OccupantDefeatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We defended {1} ({2} versus {3}) against {0}. We destroyed {4}, captured {5}, and retreated {6}. We lost {4}..
        /// </summary>
        internal static string OccupantVictoryFormat {
            get {
                return ResourceManager.GetString("OccupantVictoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username is already in use..
        /// </summary>
        internal static string RegisterErrorMessage {
            get {
                return ResourceManager.GetString("RegisterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        internal static string VictoryMessage {
            get {
                return ResourceManager.GetString("VictoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection.
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone {0}.
        /// </summary>
        internal static string ZoneFormat {
            get {
                return ResourceManager.GetString("ZoneFormat", resourceCulture);
            }
        }
    }
}
