// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rebus.Server;

#nullable disable

namespace Rebus.Server.Migrations
{
    [DbContext(typeof(RebusDbContext))]
    [Migration("20220227014915_MicrocomputerMigration")]
    partial class MicrocomputerMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("ArgumentSignatureCommandSignature", b =>
                {
                    b.Property<int>("ArgumentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArgumentsId", "CommandsId");

                    b.HasIndex("CommandsId");

                    b.ToTable("ArgumentSignatureCommandSignature");
                });

            modelBuilder.Entity("ConceptConceptSignature", b =>
                {
                    b.Property<int>("ConceptsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignaturesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConceptsId", "SignaturesId");

                    b.HasIndex("SignaturesId");

                    b.ToTable("ConceptConceptSignature");
                });

            modelBuilder.Entity("ConceptSignatureToken", b =>
                {
                    b.Property<int>("AdjectivesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignaturesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdjectivesId", "SignaturesId");

                    b.HasIndex("SignaturesId");

                    b.ToTable("ConceptSignatureToken");
                });

            modelBuilder.Entity("Rebus.Server.ArgumentSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Argument")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Argument", "Type")
                        .IsUnique();

                    b.ToTable("ArgumentSignature");
                });

            modelBuilder.Entity("Rebus.Server.CommandPrototype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("CommandPrototype");
                });

            modelBuilder.Entity("Rebus.Server.CommandSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdverbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdverbId");

                    b.HasIndex("CommandId");

                    b.HasIndex("VerbId");

                    b.ToTable("CommandSignature");
                });

            modelBuilder.Entity("Rebus.Server.Concept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discriminator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Concept");

                    b.HasDiscriminator<int>("Discriminator");
                });

            modelBuilder.Entity("Rebus.Server.ConceptSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubstantiveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("SubstantiveId");

                    b.ToTable("ConceptSignature");
                });

            modelBuilder.Entity("Rebus.Server.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Rebus.Server.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arguments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Arguments");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("Rebus.Server.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Token");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.MicrocomputerConcept", b =>
                {
                    b.HasBaseType("Rebus.Server.Concept");

                    b.ToTable("Concept");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Rebus.Server.Concepts.RegionConcept", b =>
                {
                    b.HasBaseType("Rebus.Server.Concept");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.ToTable("Concept");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Rebus.Server.Concepts.SpacecraftConcept", b =>
                {
                    b.HasBaseType("Rebus.Server.Concept");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("RegionId");

                    b.ToTable("Concept");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("ArgumentSignatureCommandSignature", b =>
                {
                    b.HasOne("Rebus.Server.ArgumentSignature", null)
                        .WithMany()
                        .HasForeignKey("ArgumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rebus.Server.CommandSignature", null)
                        .WithMany()
                        .HasForeignKey("CommandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConceptConceptSignature", b =>
                {
                    b.HasOne("Rebus.Server.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rebus.Server.ConceptSignature", null)
                        .WithMany()
                        .HasForeignKey("SignaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConceptSignatureToken", b =>
                {
                    b.HasOne("Rebus.Server.Token", null)
                        .WithMany()
                        .HasForeignKey("AdjectivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rebus.Server.ConceptSignature", null)
                        .WithMany()
                        .HasForeignKey("SignaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rebus.Server.CommandSignature", b =>
                {
                    b.HasOne("Rebus.Server.Token", "Adverb")
                        .WithMany()
                        .HasForeignKey("AdverbId");

                    b.HasOne("Rebus.Server.CommandPrototype", "Command")
                        .WithMany("Signatures")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rebus.Server.Token", "Verb")
                        .WithMany()
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adverb");

                    b.Navigation("Command");

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("Rebus.Server.Concept", b =>
                {
                    b.HasOne("Rebus.Server.Player", "Player")
                        .WithMany("Concepts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Rebus.Server.ConceptSignature", b =>
                {
                    b.HasOne("Rebus.Server.Token", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("Rebus.Server.Token", "Substantive")
                        .WithMany()
                        .HasForeignKey("SubstantiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Substantive");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.SpacecraftConcept", b =>
                {
                    b.HasOne("Rebus.Server.Concepts.RegionConcept", "Region")
                        .WithMany("Spacecraft")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Rebus.Server.CommandPrototype", b =>
                {
                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("Rebus.Server.Player", b =>
                {
                    b.Navigation("Concepts");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.RegionConcept", b =>
                {
                    b.Navigation("Spacecraft");
                });
#pragma warning restore 612, 618
        }
    }
}
