// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rebus.Server;

#nullable disable

namespace Rebus.Server.Migrations
{
    [DbContext(typeof(RebusDbContext))]
    [Migration("20220303034406_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("ConceptSignatureToken", b =>
                {
                    b.Property<string>("AdjectivesValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("SignaturesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdjectivesValue", "SignaturesId");

                    b.HasIndex("SignaturesId");

                    b.ToTable("ConceptSignatureToken");
                });

            modelBuilder.Entity("Rebus.Server.CommandSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdverbValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerbValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdverbValue");

                    b.HasIndex("VerbValue");

                    b.ToTable("CommandSignature");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Spacecraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Spacecraft");
                });

            modelBuilder.Entity("Rebus.Server.ConceptSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpacecraftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubstantiveValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleValue");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Priority");

                    b.HasIndex("SpacecraftId");

                    b.HasIndex("SubstantiveValue");

                    b.ToTable("ConceptSignature");
                });

            modelBuilder.Entity("Rebus.Server.Resource", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arguments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key", "Arguments", "Value");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("Rebus.Server.Token", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Value");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("ConceptSignatureToken", b =>
                {
                    b.HasOne("Rebus.Server.Token", null)
                        .WithMany()
                        .HasForeignKey("AdjectivesValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rebus.Server.ConceptSignature", null)
                        .WithMany()
                        .HasForeignKey("SignaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rebus.Server.CommandSignature", b =>
                {
                    b.HasOne("Rebus.Server.Token", null)
                        .WithMany()
                        .HasForeignKey("AdverbValue");

                    b.HasOne("Rebus.Server.Token", null)
                        .WithMany()
                        .HasForeignKey("VerbValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Spacecraft", b =>
                {
                    b.HasOne("Rebus.Server.Concepts.Player", null)
                        .WithMany("Spacecraft")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rebus.Server.ConceptSignature", b =>
                {
                    b.HasOne("Rebus.Server.Token", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleValue");

                    b.HasOne("Rebus.Server.Concepts.Player", null)
                        .WithMany("Signatures")
                        .HasForeignKey("PlayerId");

                    b.HasOne("Rebus.Server.Concepts.Spacecraft", null)
                        .WithMany("Signatures")
                        .HasForeignKey("SpacecraftId");

                    b.HasOne("Rebus.Server.Token", "Substantive")
                        .WithMany()
                        .HasForeignKey("SubstantiveValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Substantive");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Player", b =>
                {
                    b.Navigation("Signatures");

                    b.Navigation("Spacecraft");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Spacecraft", b =>
                {
                    b.Navigation("Signatures");
                });
#pragma warning restore 612, 618
        }
    }
}
