// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rebus.Server;

#nullable disable

namespace Rebus.Server.Migrations
{
    [DbContext(typeof(RebusDbContext))]
    partial class RebusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Rebus.Server.Adjective", b =>
                {
                    b.Property<string>("TokenValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenValue", "ConceptId");

                    b.HasIndex("ConceptId");

                    b.ToTable("Adjective");
                });

            modelBuilder.Entity("Rebus.Server.CommandSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdverbValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerbValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdverbValue");

                    b.HasIndex("VerbValue");

                    b.ToTable("Command");
                });

            modelBuilder.Entity("Rebus.Server.Concept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubstantiveValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(' ');

                    b.HasKey("Id");

                    b.HasIndex("ArticleValue");

                    b.HasIndex("SubstantiveValue");

                    b.HasIndex("Q", "R");

                    b.ToTable("Concept");

                    b.HasDiscriminator<char>("Type");
                });

            modelBuilder.Entity("Rebus.Server.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Credential")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Rebus.Server.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arguments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Arguments", "Value")
                        .IsUnique();

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("Rebus.Server.Token", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Value");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Direction", b =>
                {
                    b.HasBaseType("Rebus.Server.Concept");

                    b.HasIndex("PlayerId");

                    b.ToTable("Concept");

                    b.HasDiscriminator().HasValue('D');
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Planet", b =>
                {
                    b.HasBaseType("Rebus.Server.Concept");

                    b.HasIndex("PlayerId");

                    b.ToTable("Concept");

                    b.HasDiscriminator().HasValue('P');
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Spacecraft", b =>
                {
                    b.HasBaseType("Rebus.Server.Concept");

                    b.HasIndex("PlayerId");

                    b.ToTable("Concept");

                    b.HasDiscriminator().HasValue('S');
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Star", b =>
                {
                    b.HasBaseType("Rebus.Server.Concept");

                    b.HasIndex("PlayerId");

                    b.ToTable("Concept");

                    b.HasDiscriminator().HasValue('T');
                });

            modelBuilder.Entity("Rebus.Server.Adjective", b =>
                {
                    b.HasOne("Rebus.Server.Concept", null)
                        .WithMany("Adjectives")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rebus.Server.Token", "Token")
                        .WithMany("Adjectives")
                        .HasForeignKey("TokenValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Rebus.Server.CommandSignature", b =>
                {
                    b.HasOne("Rebus.Server.Token", null)
                        .WithMany()
                        .HasForeignKey("AdverbValue");

                    b.HasOne("Rebus.Server.Token", null)
                        .WithMany()
                        .HasForeignKey("VerbValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rebus.Server.Concept", b =>
                {
                    b.HasOne("Rebus.Server.Token", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleValue");

                    b.HasOne("Rebus.Server.Token", "Substantive")
                        .WithMany()
                        .HasForeignKey("SubstantiveValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Substantive");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Direction", b =>
                {
                    b.HasOne("Rebus.Server.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Planet", b =>
                {
                    b.HasOne("Rebus.Server.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Spacecraft", b =>
                {
                    b.HasOne("Rebus.Server.Player", "Player")
                        .WithMany("Spacecraft")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Rebus.Server.Concepts.Star", b =>
                {
                    b.HasOne("Rebus.Server.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Rebus.Server.Concept", b =>
                {
                    b.Navigation("Adjectives");
                });

            modelBuilder.Entity("Rebus.Server.Player", b =>
                {
                    b.Navigation("Spacecraft");
                });

            modelBuilder.Entity("Rebus.Server.Token", b =>
                {
                    b.Navigation("Adjectives");
                });
#pragma warning restore 612, 618
        }
    }
}
